import { StyleSheet } from "react-native";

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 100,
    },
    header: {
      paddingTop: 8,
      marginBottom: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    screenTitle: {
      fontSize: 28,
      fontWeight: "700" as const,
      color: colors.text,
    },
    headerButtons: {
      flexDirection: "row",
      gap: 12,
    },
    iconHeaderButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 6,
    },
    iconHeaderButtonText: {
      fontSize: 13,
      color: colors.text,
      fontWeight: "500" as const,
    },
    emptyState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 100,
    },
    emptyTitle: {
      fontSize: 24,
      fontWeight: "600" as const,
      color: colors.text,
      marginTop: 16,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: "center",
      paddingHorizontal: 40,
    },
    section: {
      marginTop: 8,
      marginBottom: 8,
    },
    itemSeparator: {
      height: 12,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: "700" as const,
      color: colors.text,
      marginBottom: 8,
    },
    taskCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    overdueTaskCard: {
      borderWidth: 1,
      borderColor: colors.error,
    },
    dueSoonTaskCard: {
      borderWidth: 1,
      borderColor: colors.warning,
    },
    taskInfo: {
      flex: 1,
      minWidth: 0,
    },
    taskTitle: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.text,
      marginBottom: 2,
      flexShrink: 1,
    },
    taskVehicle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 2,
      flexShrink: 1,
    },
    taskOverdue: {
      fontSize: 14,
      fontWeight: "500" as const,
      color: colors.error,
    },
    taskDueSoon: {
      fontSize: 14,
      fontWeight: "500" as const,
      color: colors.warning,
    },
    taskScheduled: {
      fontSize: 14,
      color: colors.primary,
    },

    filterBadge: {
      position: "absolute",
      top: 0,
      right: 0,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.error,
    },
    summaryCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    summaryItem: {
      alignItems: "center",
      flex: 1,
    },
    summaryLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    summaryValue: {
      fontSize: 24,
      fontWeight: "700" as const,
      color: colors.text,
    },
    summaryDivider: {
      width: 1,
      height: 40,
      backgroundColor: colors.border,
    },
    modalHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
      paddingHorizontal: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "700" as const,
      color: colors.text,
    },
    modalHeaderLink: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: "500" as const,
    },
    modalScrollView: {
      flexShrink: 1,
    },
    modalScrollContent: {
      paddingBottom: 24,
      paddingHorizontal: 16,
    },
    filterSection: {
      marginBottom: 24,
    },
    filterSectionTitle: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.text,
      marginBottom: 12,
    },
    categoryChips: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    categoryChip: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      flexGrow: 1,
      flexBasis: "40%",
    },
    categoryChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    categoryChipText: {
      fontSize: 13,
      color: colors.text,
      fontWeight: "500" as const,
      flexShrink: 1,
    },
    categoryChipTextActive: {
      color: "#FFFFFF",
      fontWeight: "600" as const,
    },
    sortOptionsList: {
      gap: 0,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    sortOptionItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    sortOptionItemActive: {
      backgroundColor: colors.card,
    },
    sortOptionText: {
      fontSize: 16,
      color: colors.text,
      fontWeight: "500" as const,
    },
    sortOptionTextActive: {
      color: colors.primary,
      fontWeight: "600" as const,
    },
    sortOptionIndicator: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.primary,
    },
    sortDirectionBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sortDirectionText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: "500" as const,
    },
    quickFiltersRow: {
      flexDirection: "row",
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 4,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    quickFilterChip: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    quickFilterChipActive: {
      backgroundColor: colors.primary,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    quickFilterChipText: {
      fontSize: 13,
      fontWeight: "500" as const,
      color: colors.textSecondary,
    },
    quickFilterChipTextActive: {
      color: "#FFFFFF",
      fontWeight: "600" as const,
    },
    modalCancel: {
      marginTop: 8,
      paddingVertical: 12,
    },
    modalCancelText: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.primary,
      textAlign: "center",
    },
  });
