import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "@/contexts/ThemeContext";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export const createImagePositionModalStyles = (colors: Colors) =>
  StyleSheet.create({
    modalOverlay: {
      flex: 1,
      backgroundColor: "#050505",
    },
    container: {
      flex: 1,
      backgroundColor: "#000",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      height: 64,
      borderBottomWidth: 1,
      borderBottomColor: "rgba(255,255,255,0.08)",
      backgroundColor: "#000",
    },
    headerContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    workspace: {
      flex: 1,
      backgroundColor: "#050505",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
    },
    iconButton: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: "rgba(255,255,255,0.05)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
    },
    headerButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
    },
    primaryIconButton: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    stepTitleContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: "rgba(255,255,255,0.05)",
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
    },
    stepTitle: {
      color: "#FFF",
      fontSize: 14,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    stepIcon: {
      opacity: 0.9,
    },
    footerAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 16,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
    },
    footerActionText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "700",
      letterSpacing: -0.3,
    },
    navigation: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingVertical: 20,
      backgroundColor: "#161618",
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.08)",
    },
    navButton: {
      height: 54,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 24,
      minWidth: 120,
    },
    cancelButton: {
      backgroundColor: "rgba(255,255,255,0.05)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
    },
    confirmButton: {
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    buttonText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "700",
      letterSpacing: -0.3,
    },
    cancelButtonText: {
      color: "rgba(255,255,255,0.6)",
      fontSize: 16,
      fontWeight: "600",
    },
    previewTitle: {
      position: "absolute",
      top: -30,
      left: 10,
      color: "rgba(255,255,255,0.4)",
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    fullImageBackground: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
    },
    titleContainer: { alignItems: "center" },
    title: {
      color: "#FFF",
      fontSize: 17,
      fontWeight: "700",
      letterSpacing: -0.4,
    },
    stepIndicator: {
      color: "rgba(255,255,255,0.6)",
      fontSize: 13,
      marginTop: 4,
      fontWeight: "500",
    },
    backgroundFullCover: {
      position: "absolute",
      overflow: "visible",
    },
    frameContainer: {
      position: "absolute",
      overflow: "hidden",
      backgroundColor: "#1C1C1E",
    },
    imageWrapper: { position: "absolute", top: 0, left: 0 },
    frameBorder: {
      ...StyleSheet.absoluteFillObject,
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.2)",
      borderRadius: 24,
      zIndex: 10,
    },
    detailsCurveContainer: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
    },
    headerOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      backgroundColor: "#000",
      zIndex: 50,
    },
    controlsPanel: {
      backgroundColor: "#161618",
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -12 },
      shadowOpacity: 0.8,
      shadowRadius: 24,
      elevation: 40,
    },
    controlsContent: {
      paddingHorizontal: 20,
      paddingTop: 24,
    },
    sliderRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 4,
      gap: 16,
    },
    slider: {
      flex: 1,
      height: 40,
    },
    presetsWrapper: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 16,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.05)",
    },
    presetButton: {
      alignItems: "center",
      gap: 8,
      flex: 1,
      paddingVertical: 8,
    },
    presetLabel: {
      color: "rgba(255,255,255,0.4)",
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
  });
