import { StyleSheet, Platform } from "react-native";
import { Colors } from "@/contexts/ThemeContext";

export const createTechnicalSpecsStyles = (colors: Colors) =>
  StyleSheet.create({
    container: {
      paddingHorizontal: 20,
      marginTop: 24,
      marginBottom: 8,
    },
    title: {
      fontSize: 22,
      fontWeight: "800",
      marginBottom: 16,
      color: colors.text,
      letterSpacing: 0.5,
    },
    grid: {
      gap: 16,
    },
    row: {
      flexDirection: "row",
      gap: 12,
    },
    specItem: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 12,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    iconContainer: {
      width: 36,
      height: 36,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    specTextContainer: {
      flex: 1,
    },
    specLabel: {
      fontSize: 10,
      textTransform: "uppercase",
      letterSpacing: 1,
      color: colors.textSecondary,
      marginBottom: 2,
      fontWeight: "700",
    },
    specValue: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    tireSection: {
      padding: 16,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    tireHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 12,
    },
    tireTitle: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    tireContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    tireValue: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text,
    },
    pressureBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
      backgroundColor: colors.primary + "10",
    },
    pressureText: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.primary,
    },
    vinSection: {
      padding: 16,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    vinValue: {
      fontSize: 14,
      fontWeight: "700",
      fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
      letterSpacing: 1.5,
      color: colors.text,
      opacity: 0.9,
    },
    sectionHeader: {
      marginTop: 16,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: colors.text,
    },
  });
