import { StyleSheet } from "react-native";

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingBottom: 100,
    },
    header: {
      paddingTop: 8,
      marginBottom: 12,
    },
    titleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 24,
    },
    screenTitle: {
      fontSize: 28,
      fontWeight: "700" as const,
      color: colors.text,
    },
    headerButtonsRow: {
      flexDirection: "row",
      justifyContent: "flex-start",
      gap: 12,
    },
    iconHeaderButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 6,
    },
    iconHeaderButtonText: {
      fontSize: 13,
      color: colors.text,
      fontWeight: "500" as const,
    },
    filterSection: {
      marginBottom: 14,
      gap: 8,
    },
    filterSectionTitle: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.text,
      marginBottom: 12,
      marginLeft: 4,
    },
    filterChips: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingVertical: 4,
    },
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      marginRight: 4,
    },
    filterActionsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      marginTop: 12,
      marginBottom: 16,
    },
    clearFiltersButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: "transparent",
    },
    clearFiltersText: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: "500" as const,
      textDecorationLine: "underline",
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterChipText: {
      color: colors.text,
      fontWeight: "500" as const,
    },
    filterChipTextActive: {
      color: "#FFFFFF",
    },
    modalHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    modalHeaderLink: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: "500" as const,
      textDecorationLine: "underline",
    },
    toggleButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignSelf: "flex-start",
    },
    toggleButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    toggleButtonText: {
      color: colors.text,
      fontWeight: "600" as const,
    },
    toggleButtonTextActive: {
      color: "#FFFFFF",
    },
    emptyState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 100,
    },
    emptyTitle: {
      fontSize: 24,
      fontWeight: "600" as const,
      color: colors.text,
      marginTop: 16,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: "center",
      paddingHorizontal: 40,
    },
    vehicleList: {
      gap: 12,
    },
    itemSeparator: {
      height: 12,
    },
    vehicleCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    vehicleImage: {
      width: 80,
      height: 80,
      borderRadius: 12,
      backgroundColor: colors.border,
    },
    vehicleImagePlaceholder: {
      width: 80,
      height: 80,
      borderRadius: 12,
      backgroundColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
    },
    vehicleInfo: {
      flex: 1,
      marginLeft: 12,
      minWidth: 0,
    },
    vehicleHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    vehicleName: {
      fontSize: 18,
      fontWeight: "600" as const,
      color: colors.text,
      marginBottom: 4,
      flexShrink: 1,
    },
    archivedBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      backgroundColor: colors.warning + "30",
    },
    archivedBadgeText: {
      fontSize: 12,
      color: colors.warning,
      fontWeight: "600" as const,
    },
    vehicleDetails: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 2,
      flexShrink: 1,
    },
    vehicleMileage: {
      fontSize: 14,
      fontWeight: "500" as const,
      color: colors.primary,
    },
    categoryBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 6,
    },
    categoryBadgeText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: "500" as const,
    },
    alertBadge: {
      backgroundColor: colors.error,
      borderRadius: 12,
      width: 24,
      height: 24,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 8,
    },
    alertBadgeText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "700" as const,
    },
    addButton: {
      position: "absolute",
      right: 16,
      bottom: 16,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.textSecondary,
      marginBottom: 12,
    },
    modalAction: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      marginTop: 8,
    },
    modalActionText: {
      fontSize: 15,
      color: colors.text,
      fontWeight: "500" as const,
    },
    quickRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 4,
      marginBottom: 4,
      gap: 12,
    },
    quickItem: {
      flex: 1,
      alignItems: "center",
      gap: 8,
    },
    quickIconButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 3,
    },
    modalScrollView: {
      flexGrow: 0,
    },
    modalScrollContent: {
      paddingBottom: 8,
    },
    quickLabel: {
      fontSize: 12,
      color: colors.text,
      textAlign: "center",
      fontWeight: "500" as const,
    },
    modalCancel: {
      marginTop: 8,
      paddingVertical: 12,
    },
    modalCancelText: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.primary,
      textAlign: "center",
    },
    actionsList: {
      gap: 12,
      paddingBottom: 20,
    },
    actionItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    actionIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.background,
      justifyContent: "center",
      alignItems: "center",
    },
    actionContent: {
      flex: 1,
    },
    actionTitle: {
      fontSize: 16,
      fontWeight: "600" as const,
      color: colors.text,
      marginBottom: 2,
    },
    actionDescription: {
      fontSize: 13,
      color: colors.textSecondary,
    },
  });
